name: Build PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add Pull Request Reviewers
        uses: AveryCameronUofR/add-reviewer-gh-action@1.0.4
        with:
          reviewers: "Kuyoh"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: ./.github/actions/setenv
        with:
          varFilePath: ./*.env

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and test Alpine
        id: alpine_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile.alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASE_IMAGE=alpine:${{ env.ALPINE_VERSION }}
            VCPKG_VERSION=${{ env.VCPKG_VERSION }}
          push: false

      - name: Build and test Ubuntu
        id: ubuntu_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile.debian
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASE_IMAGE=ubuntu:${{ env.UBUNTU_VERSION }}
            VCPKG_VERSION=${{ env.VCPKG_VERSION }}
          push: false
